module.exports = {
  rootDir: '.',
  testEnvironment: 'node',
  testMatch: [
    '<rootDir>/libraries/nestjs-libraries/src/database/prisma/pipelines/**/*.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/database/prisma/autopost/**/*.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/database/prisma/context-documents/**/*.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/chat/tools/pipeline.context-document.tools.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/chat/tools/context-document.tools.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/chat/tools/expertise.tools.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/chat/tools/agent-skill.tools.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/chat/tools/follower.tools.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/chat/load.tools.service.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/database/prisma/posts/posts.repository.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/database/prisma/posts/posts.service.edit.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/database/prisma/logs/**/*.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/database/prisma/admin-schedule-logs/**/*.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/database/prisma/channel-interactions/**/*.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/database/prisma/conversions/**/*.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/channel-strategies/**/*.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/database/prisma/integrations/integration.followers.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/database/prisma/database.module.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/database/prisma/integrations/integration.customer.reorder.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/integrations/social/follower.sorts.spec.ts',
    '<rootDir>/apps/backend/src/api/routes/followers.controller.spec.ts',
    '<rootDir>/apps/backend/src/api/routes/integrations.controller.spec.ts',
    '<rootDir>/apps/backend/src/api/routes/conversions.controller.spec.ts',
    '<rootDir>/apps/backend/src/api/routes/conversion-webhooks.controller.spec.ts',
    '<rootDir>/apps/backend/src/public-api/routes/v1/public.integrations.controller.spec.ts',
    '<rootDir>/apps/backend/src/api/routes/context-documents.controller.spec.ts',
    '<rootDir>/apps/backend/src/api/routes/channel-webhooks.controller.spec.ts',
    '<rootDir>/apps/orchestrator/src/activities/post.activity.spec.ts',
    '<rootDir>/apps/orchestrator/src/activities/pipeline.activity.spec.ts',
    '<rootDir>/apps/orchestrator/src/activities/channel-relationship-grade.activity.spec.ts',
    '<rootDir>/apps/orchestrator/src/workflows/autopost.workflow.v2.spec.ts',
    '<rootDir>/apps/frontend/src/components/settings/logs.component.spec.tsx',
    '<rootDir>/apps/frontend/src/components/settings/channels.component.spec.tsx',
    '<rootDir>/apps/frontend/src/components/help/help-content.spec.tsx',
    '<rootDir>/apps/frontend/src/components/help/help.drawer.spec.tsx',
    '<rootDir>/libraries/nestjs-libraries/src/integrations/social/file.provider.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/integrations/webhook.file.sink.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/integrations/social/x.provider.interactions.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/integrations/social/x.provider.edit.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/integrations/social/mastodon.provider.edit.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/temporal/infinite.workflow.register.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/temporal/relationship-grade.schedule.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/temporal/relationship-grade.schedule.service.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/temporal/follower-bot-score.schedule.service.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/temporal/follower-bot-score.schedule.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/temporal/hot-triage.schedule.service.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/temporal/admin-schedule.workflow.service.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/dtos/admin/relationship-grade.schedule.dto.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/dtos/admin/follower-bot-score.schedule.dto.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/configuration/admin-webauthn.configuration.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/database/prisma/admin-passkeys/**/*.spec.ts',
    '<rootDir>/apps/backend/src/api/routes/admin-auth.controller.spec.ts',
    '<rootDir>/apps/backend/src/api/routes/admin-step-up-policies.spec.ts',
    '<rootDir>/apps/backend/src/services/auth/admin-step-up.guard.spec.ts',
    '<rootDir>/apps/backend/src/services/auth/auth.middleware.spec.ts',
    '<rootDir>/apps/orchestrator/src/workflows/channel-relationship-grade.workflow.spec.ts',
    '<rootDir>/apps/orchestrator/src/workflows/channel-relationship-grade.workflow.v2.spec.ts',
    '<rootDir>/apps/orchestrator/src/workflows/channel-lead-bridge.workflow.v1.spec.ts',
    '<rootDir>/apps/orchestrator/src/workflows/channel-lead-bridge-admin-trigger.workflow.v1.spec.ts',
    '<rootDir>/apps/orchestrator/src/workflows/channel-cultivate.workflow.v1.spec.ts',
    '<rootDir>/apps/orchestrator/src/workflows/channel-hot-materialization.workflow.v1.spec.ts',
    '<rootDir>/apps/orchestrator/src/activities/channel-hot-materialization.activity.spec.ts',
    '<rootDir>/apps/orchestrator/src/activities/channel-cultivate.activity.spec.ts',
    '<rootDir>/apps/frontend/src/components/admin/admin-schedule.component.spec.tsx',
    '<rootDir>/apps/frontend/src/components/admin/use.admin-schedule-logs.spec.tsx',
    '<rootDir>/apps/frontend/src/components/admin/admin-passkey.utils.spec.ts',
    '<rootDir>/apps/frontend/src/components/admin/admin-passkey-flow.spec.tsx',
    '<rootDir>/apps/frontend/src/components/layout/admin.component.spec.tsx',
    '<rootDir>/apps/frontend/src/components/layout/layout.context.spec.ts',
    '<rootDir>/apps/frontend/src/components/layout/logout.component.spec.tsx',
    '<rootDir>/apps/frontend/src/components/layout/use.dismissed.alerts.spec.tsx',
    '<rootDir>/apps/frontend/src/components/layout/copilot.assistant.popup.spec.tsx',
    '<rootDir>/apps/frontend/src/components/layout/copilot.assistant.popup.size.spec.ts',
    '<rootDir>/libraries/helpers/src/utils/custom.fetch.func.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/database/prisma/channel-analytics/**/*.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/integrations/social/x.provider.analytics.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/integrations/social/youtube.provider.followers.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/integrations/social/x.provider.followers.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/integrations/social/bluesky.provider.followers.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/integrations/social/mastodon.provider.followers.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/integrations/social/farcaster.provider.followers.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/integrations/social/channel-follower-totals.analytics.spec.ts',
    '<rootDir>/apps/orchestrator/src/workflows/channel-analytics-snapshot.workflow.v2.spec.ts',
    '<rootDir>/apps/orchestrator/src/activities/channel-analytics-snapshot.activity.spec.ts',
    '<rootDir>/apps/orchestrator/src/workflows/conversion-evaluation.workflow.spec.ts',
    '<rootDir>/apps/orchestrator/src/activities/conversion-evaluation.activity.spec.ts',
    '<rootDir>/apps/frontend/src/components/platform-analytics/render.analytics.spec.tsx',
    '<rootDir>/apps/frontend/src/components/dashboard/dashboard.analytics.layout.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/database/prisma/users/users.repository.dashboard-preferences.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/database/prisma/users/users.repository.dismissed-alerts.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/dtos/users/dismissed-alert.dto.spec.ts',
    '<rootDir>/libraries/helpers/src/utils/posts.list.minify.spec.ts',
    '<rootDir>/libraries/helpers/src/utils/count.length.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/imgflip/**/*.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/database/prisma/media/media.service.spec.ts',
    '<rootDir>/apps/orchestrator/src/workflows/pipeline-workflows/**/*.spec.ts',
    '<rootDir>/apps/frontend/src/components/pipelines/**/*.spec.ts',
    '<rootDir>/apps/frontend/src/components/pipelines/**/*.spec.tsx',
    '<rootDir>/apps/frontend/src/components/context-documents/**/*.spec.tsx',
    '<rootDir>/apps/frontend/src/components/rules/rule.utils.spec.ts',
    '<rootDir>/apps/frontend/src/components/rules/use.rule.detail.spec.ts',
    '<rootDir>/apps/frontend/src/components/rules/use.rule.mutations.spec.ts',
    '<rootDir>/apps/frontend/src/components/rules/use.rules.list.spec.ts',
    '<rootDir>/apps/frontend/src/components/rules/condition.editor.spec.tsx',
    '<rootDir>/apps/frontend/src/components/new-launch/open-graph/**/*.spec.ts',
    '<rootDir>/apps/frontend/src/components/media/**/*.spec.tsx',
    '<rootDir>/apps/frontend/src/components/agents/**/*.spec.tsx',
    '<rootDir>/apps/frontend/src/components/agents/**/*.spec.ts',
    '<rootDir>/apps/frontend/src/components/launches/channels.sidebar.spec.tsx',
    '<rootDir>/apps/frontend/src/components/launches/helpers/last-channel.spec.ts',
    '<rootDir>/apps/frontend/src/components/followers/**/*.spec.tsx',
    '<rootDir>/scripts/users-reset-admin-passkeys.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/integrations/social/x.provider.rules.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/integrations/social/linkedin.page.provider.rules.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/integrations/social/bluesky.provider.rules.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/integrations/social/threads.provider.rules.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/database/prisma/rules/post-rules.domain.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/dtos/rules/rule.dto.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/database/prisma/rules/post-rules.repository.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/database/prisma/rules/post-rules.service.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/database/prisma/rules/post-rules.execution.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/database/prisma/rules/post-rules.reschedule.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/database/prisma/rules/post-rules.posts.integration.spec.ts',
    '<rootDir>/libraries/nestjs-libraries/src/database/prisma/rules/post-rules.pipeline.integration.spec.ts',
    '<rootDir>/apps/backend/src/api/routes/rules.controller.spec.ts',
  ],
  transform: {
    '^.+\\.tsx?$': [
      'ts-jest',
      {
        tsconfig: {
          module: 'commonjs',
          jsx: 'react-jsx',
          esModuleInterop: true,
          isolatedModules: true,
          target: 'es2019',
          lib: ['es2020', 'dom'],
        },
      },
    ],
  },
  moduleNameMapper: {
    '\\.css$': '<rootDir>/jest.style.mock.js',
    '^overlayscrollbars-react$':
      '<rootDir>/jest.overlayscrollbars-react.mock.js',
    '^canvas$': '<rootDir>/jest.canvas.mock.js',
    '^@gitroom/nestjs-libraries/(.*)$':
      '<rootDir>/libraries/nestjs-libraries/src/$1',
    '^@gitroom/orchestrator/(.*)$': '<rootDir>/apps/orchestrator/src/$1',
    '^@gitroom/backend/(.*)$': '<rootDir>/apps/backend/src/$1',
    '^@gitroom/helpers/(.*)$': '<rootDir>/libraries/helpers/src/$1',
    '^@gitroom/react/(.*)$':
      '<rootDir>/libraries/react-shared-libraries/src/$1',
    '^@gitroom/frontend/(.*)$': '<rootDir>/apps/frontend/src/$1',
  },
};
