// Generated by scripts/build-docs-nav.mjs. Do not edit manually.

import type { DefaultTheme } from 'vitepress'

export const sidebar: DefaultTheme.SidebarItem[] = 
[
  {
    "text": "Internal Overview",
    "link": "/"
  },
  {
    "text": "Features",
    "link": "/features",
    "items": [
      {
        "text": "Multi-Channel Scheduling",
        "link": "/features#multi-channel-scheduling"
      },
      {
        "text": "Pipelines",
        "link": "/features#pipelines"
      },
      {
        "text": "Autopost",
        "link": "/features#autopost"
      },
      {
        "text": "Rules",
        "link": "/features#rules"
      },
      {
        "text": "Agents And Assisted Creation",
        "link": "/features#agents-and-assisted-creation"
      },
      {
        "text": "Analytics",
        "link": "/features#analytics"
      },
      {
        "text": "Followers And Audience Tools",
        "link": "/features#followers-and-audience-tools"
      },
      {
        "text": "Channel Interaction Tracking",
        "link": "/features#channel-interaction-tracking"
      },
      {
        "text": "Team Management",
        "link": "/features#team-management"
      },
      {
        "text": "Media Library",
        "link": "/features#media-library"
      },
      {
        "text": "Context Documents",
        "link": "/features#context-documents"
      },
      {
        "text": "Automation And API Access",
        "link": "/features#automation-and-api-access"
      },
      {
        "text": "Self-Hosted And Hosted Usage",
        "link": "/features#self-hosted-and-hosted-usage"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Architecture",
    "link": "/architecture",
    "items": [
      {
        "text": "Monorepo Boundaries",
        "link": "/architecture#monorepo-boundaries"
      },
      {
        "text": "Backend Layering",
        "link": "/architecture#backend-layering"
      },
      {
        "text": "Authentication Boundaries",
        "link": "/architecture#authentication-boundaries"
      },
      {
        "text": "Provider Boundaries",
        "link": "/architecture#provider-boundaries"
      },
      {
        "text": "Background Work",
        "link": "/architecture#background-work"
      },
      {
        "text": "Data Ownership",
        "link": "/architecture#data-ownership"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Backend API",
    "link": "/backend-api",
    "items": [
      {
        "text": "Module Wiring",
        "link": "/backend-api#module-wiring"
      },
      {
        "text": "Request Flow",
        "link": "/backend-api#request-flow"
      },
      {
        "text": "Organization Context",
        "link": "/backend-api#organization-context"
      },
      {
        "text": "Authorization",
        "link": "/backend-api#authorization"
      },
      {
        "text": "Endpoint Discovery",
        "link": "/backend-api#endpoint-discovery"
      },
      {
        "text": "Adding A Route",
        "link": "/backend-api#adding-a-route"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Public API",
    "link": "/public-api",
    "items": [
      {
        "text": "Module Wiring",
        "link": "/public-api#module-wiring"
      },
      {
        "text": "Route Surface",
        "link": "/public-api#route-surface"
      },
      {
        "text": "Authentication",
        "link": "/public-api#authentication"
      },
      {
        "text": "Validation And Safety",
        "link": "/public-api#validation-and-safety"
      },
      {
        "text": "Relationship To SDKs",
        "link": "/public-api#relationship-to-sdks"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Strategy-Aware Conversions",
    "link": "/conversions",
    "items": [
      {
        "text": "Strategy Meanings",
        "link": "/conversions#strategy-meanings"
      },
      {
        "text": "HTTP Surfaces",
        "link": "/conversions#http-surfaces",
        "items": [
          {
            "text": "Authenticated app API",
            "link": "/conversions#authenticated-app-api"
          },
          {
            "text": "Public API (/public/v1)",
            "link": "/conversions#public-api-publicv1"
          },
          {
            "text": "Conversion webhooks",
            "link": "/conversions#conversion-webhooks"
          }
        ],
        "collapsed": false
      },
      {
        "text": "Goal Ingestion Examples",
        "link": "/conversions#goal-ingestion-examples",
        "items": [
          {
            "text": "Public API with click attribution",
            "link": "/conversions#public-api-with-click-attribution"
          },
          {
            "text": "Webhook goal ingestion",
            "link": "/conversions#webhook-goal-ingestion"
          },
          {
            "text": "UTM fallback (no click ID)",
            "link": "/conversions#utm-fallback-no-click-id"
          }
        ],
        "collapsed": false
      },
      {
        "text": "Click Over UTM Precedence",
        "link": "/conversions#click-over-utm-precedence"
      },
      {
        "text": "Explicit Support Resolution",
        "link": "/conversions#explicit-support-resolution"
      },
      {
        "text": "List And Summary Filters",
        "link": "/conversions#list-and-summary-filters"
      },
      {
        "text": "Idempotency And Safe Retries",
        "link": "/conversions#idempotency-and-safe-retries"
      },
      {
        "text": "Attribution Expiry",
        "link": "/conversions#attribution-expiry"
      },
      {
        "text": "Background Evaluation",
        "link": "/conversions#background-evaluation"
      },
      {
        "text": "Deployment And Rollback",
        "link": "/conversions#deployment-and-rollback"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Temporal Workflows",
    "link": "/workflows",
    "items": [
      {
        "text": "Module Wiring",
        "link": "/workflows#module-wiring"
      },
      {
        "text": "Workflows",
        "link": "/workflows#workflows"
      },
      {
        "text": "Activities",
        "link": "/workflows#activities"
      },
      {
        "text": "Compatibility Rules",
        "link": "/workflows#compatibility-rules"
      },
      {
        "text": "Retry And Timeouts",
        "link": "/workflows#retry-and-timeouts"
      },
      {
        "text": "Scheduling Patterns",
        "link": "/workflows#scheduling-patterns"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Database",
    "link": "/database",
    "items": [
      {
        "text": "Schema",
        "link": "/database#schema"
      },
      {
        "text": "Services And Repositories",
        "link": "/database#services-and-repositories"
      },
      {
        "text": "Migration Safety",
        "link": "/database#migration-safety"
      },
      {
        "text": "Self-Hosted Migration Adoption",
        "link": "/database#self-hosted-migration-adoption",
        "items": [
          {
            "text": "Fresh Database",
            "link": "/database#fresh-database"
          },
          {
            "text": "Existing Database Previously Managed By prisma db push",
            "link": "/database#existing-database-previously-managed-by-prisma-db-push"
          },
          {
            "text": "Channel strategy migration (20260823130000channelstrategy)",
            "link": "/database#channel-strategy-migration-20260823130000channelstrategy"
          }
        ],
        "collapsed": false
      },
      {
        "text": "Data Model Hotspots",
        "link": "/database#data-model-hotspots"
      },
      {
        "text": "Adding Database Behavior",
        "link": "/database#adding-database-behavior"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Frontend API Clients",
    "link": "/frontend-api",
    "items": [
      {
        "text": "Fetch Wrapper",
        "link": "/frontend-api#fetch-wrapper"
      },
      {
        "text": "SWR Pattern",
        "link": "/frontend-api#swr-pattern"
      },
      {
        "text": "Cache Keys",
        "link": "/frontend-api#cache-keys"
      },
      {
        "text": "Route Ownership",
        "link": "/frontend-api#route-ownership"
      },
      {
        "text": "Error Handling",
        "link": "/frontend-api#error-handling"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Operations",
    "link": "/operations",
    "items": [
      {
        "text": "Package Manager",
        "link": "/operations#package-manager"
      },
      {
        "text": "Common Commands",
        "link": "/operations#common-commands"
      },
      {
        "text": "App Builds",
        "link": "/operations#app-builds"
      },
      {
        "text": "Development Processes",
        "link": "/operations#development-processes"
      },
      {
        "text": "CI Notes",
        "link": "/operations#ci-notes"
      },
      {
        "text": "GitHub Pages Setup",
        "link": "/operations#github-pages-setup"
      },
      {
        "text": "Deployment-Sensitive Areas",
        "link": "/operations#deployment-sensitive-areas",
        "items": [
          {
            "text": "Conversion Rollout Checklist",
            "link": "/operations#conversion-rollout-checklist"
          }
        ],
        "collapsed": false
      }
    ],
    "collapsed": false
  },
  {
    "text": "Help",
    "collapsed": false,
    "items": [
      {
        "text": "Agent",
        "link": "/help/agent"
      },
      {
        "text": "Calendar",
        "link": "/help/calendar"
      },
      {
        "text": "Conversations",
        "link": "/help/conversation"
      },
      {
        "text": "Dashboard",
        "link": "/help/dashboard"
      },
      {
        "text": "Context",
        "link": "/help/docs"
      },
      {
        "text": "Followers",
        "link": "/help/followers"
      },
      {
        "text": "Media",
        "link": "/help/media"
      },
      {
        "text": "Pipelines",
        "link": "/help/pipelines"
      },
      {
        "text": "Rules",
        "link": "/help/rules"
      },
      {
        "text": "Settings",
        "link": "/help/settings"
      }
    ]
  }
]
